#import "TiUtils.h"
#import "TiThriftUtils.h"
#import "JpMasuidriveTiEvernoteapiModule.h"

@implementation JpMasuidriveTiEvernoteapiModule(LimitsConstValues)


-(id)EDAM_ATTRIBUTE_LEN_MIN
{
	return @"EDAM_ATTRIBUTE_LEN_MIN";
}

-(id)EDAM_ATTRIBUTE_LEN_MAX
{
	return @"EDAM_ATTRIBUTE_LEN_MAX";
}

-(id)EDAM_ATTRIBUTE_REGEX
{
	return @"EDAM_ATTRIBUTE_REGEX";
}

-(id)EDAM_ATTRIBUTE_LIST_MAX
{
	return @"EDAM_ATTRIBUTE_LIST_MAX";
}

-(id)EDAM_GUID_LEN_MIN
{
	return @"EDAM_GUID_LEN_MIN";
}

-(id)EDAM_GUID_LEN_MAX
{
	return @"EDAM_GUID_LEN_MAX";
}

-(id)EDAM_GUID_REGEX
{
	return @"EDAM_GUID_REGEX";
}

-(id)EDAM_EMAIL_LEN_MIN
{
	return @"EDAM_EMAIL_LEN_MIN";
}

-(id)EDAM_EMAIL_LEN_MAX
{
	return @"EDAM_EMAIL_LEN_MAX";
}

-(id)EDAM_EMAIL_LOCAL_REGEX
{
	return @"EDAM_EMAIL_LOCAL_REGEX";
}

-(id)EDAM_EMAIL_DOMAIN_REGEX
{
	return @"EDAM_EMAIL_DOMAIN_REGEX";
}

-(id)EDAM_EMAIL_REGEX
{
	return @"EDAM_EMAIL_REGEX";
}

-(id)EDAM_TIMEZONE_LEN_MIN
{
	return @"EDAM_TIMEZONE_LEN_MIN";
}

-(id)EDAM_TIMEZONE_LEN_MAX
{
	return @"EDAM_TIMEZONE_LEN_MAX";
}

-(id)EDAM_TIMEZONE_REGEX
{
	return @"EDAM_TIMEZONE_REGEX";
}

-(id)EDAM_MIME_LEN_MIN
{
	return @"EDAM_MIME_LEN_MIN";
}

-(id)EDAM_MIME_LEN_MAX
{
	return @"EDAM_MIME_LEN_MAX";
}

-(id)EDAM_MIME_REGEX
{
	return @"EDAM_MIME_REGEX";
}

-(id)EDAM_MIME_TYPE_GIF
{
	return @"EDAM_MIME_TYPE_GIF";
}

-(id)EDAM_MIME_TYPE_JPEG
{
	return @"EDAM_MIME_TYPE_JPEG";
}

-(id)EDAM_MIME_TYPE_PNG
{
	return @"EDAM_MIME_TYPE_PNG";
}

-(id)EDAM_MIME_TYPE_WAV
{
	return @"EDAM_MIME_TYPE_WAV";
}

-(id)EDAM_MIME_TYPE_MP3
{
	return @"EDAM_MIME_TYPE_MP3";
}

-(id)EDAM_MIME_TYPE_AMR
{
	return @"EDAM_MIME_TYPE_AMR";
}

-(id)EDAM_MIME_TYPE_MP4_VIDEO
{
	return @"EDAM_MIME_TYPE_MP4_VIDEO";
}

-(id)EDAM_MIME_TYPE_INK
{
	return @"EDAM_MIME_TYPE_INK";
}

-(id)EDAM_MIME_TYPE_PDF
{
	return @"EDAM_MIME_TYPE_PDF";
}

-(id)EDAM_MIME_TYPE_DEFAULT
{
	return @"EDAM_MIME_TYPE_DEFAULT";
}

-(id)EDAM_MIME_TYPES
{
	return @"EDAM_MIME_TYPES";
}

-(id)EDAM_COMMERCE_SERVICE_GOOGLE
{
	return @"EDAM_COMMERCE_SERVICE_GOOGLE";
}

-(id)EDAM_COMMERCE_SERVICE_PAYPAL
{
	return @"EDAM_COMMERCE_SERVICE_PAYPAL";
}

-(id)EDAM_COMMERCE_SERVICE_GIFT
{
	return @"EDAM_COMMERCE_SERVICE_GIFT";
}

-(id)EDAM_COMMERCE_SERVICE_TRIALPAY
{
	return @"EDAM_COMMERCE_SERVICE_TRIALPAY";
}

-(id)EDAM_COMMERCE_SERVICE_TRIAL
{
	return @"EDAM_COMMERCE_SERVICE_TRIAL";
}

-(id)EDAM_COMMERCE_SERVICE_GROUP
{
	return @"EDAM_COMMERCE_SERVICE_GROUP";
}

-(id)EDAM_COMMERCE_SERVICE_CYBERSOURCE
{
	return @"EDAM_COMMERCE_SERVICE_CYBERSOURCE";
}

-(id)EDAM_COMMERCE_DEFAULT_CURRENCY_COUNTRY_CODE
{
	return @"EDAM_COMMERCE_DEFAULT_CURRENCY_COUNTRY_CODE";
}

-(id)EDAM_SEARCH_QUERY_LEN_MIN
{
	return @"EDAM_SEARCH_QUERY_LEN_MIN";
}

-(id)EDAM_SEARCH_QUERY_LEN_MAX
{
	return @"EDAM_SEARCH_QUERY_LEN_MAX";
}

-(id)EDAM_SEARCH_QUERY_REGEX
{
	return @"EDAM_SEARCH_QUERY_REGEX";
}

-(id)EDAM_HASH_LEN
{
	return @"EDAM_HASH_LEN";
}

-(id)EDAM_USER_USERNAME_LEN_MIN
{
	return @"EDAM_USER_USERNAME_LEN_MIN";
}

-(id)EDAM_USER_USERNAME_LEN_MAX
{
	return @"EDAM_USER_USERNAME_LEN_MAX";
}

-(id)EDAM_USER_USERNAME_REGEX
{
	return @"EDAM_USER_USERNAME_REGEX";
}

-(id)EDAM_USER_NAME_LEN_MIN
{
	return @"EDAM_USER_NAME_LEN_MIN";
}

-(id)EDAM_USER_NAME_LEN_MAX
{
	return @"EDAM_USER_NAME_LEN_MAX";
}

-(id)EDAM_USER_NAME_REGEX
{
	return @"EDAM_USER_NAME_REGEX";
}

-(id)EDAM_TAG_NAME_LEN_MIN
{
	return @"EDAM_TAG_NAME_LEN_MIN";
}

-(id)EDAM_TAG_NAME_LEN_MAX
{
	return @"EDAM_TAG_NAME_LEN_MAX";
}

-(id)EDAM_TAG_NAME_REGEX
{
	return @"EDAM_TAG_NAME_REGEX";
}

-(id)EDAM_NOTE_TITLE_LEN_MIN
{
	return @"EDAM_NOTE_TITLE_LEN_MIN";
}

-(id)EDAM_NOTE_TITLE_LEN_MAX
{
	return @"EDAM_NOTE_TITLE_LEN_MAX";
}

-(id)EDAM_NOTE_TITLE_REGEX
{
	return @"EDAM_NOTE_TITLE_REGEX";
}

-(id)EDAM_NOTE_CONTENT_LEN_MIN
{
	return @"EDAM_NOTE_CONTENT_LEN_MIN";
}

-(id)EDAM_NOTE_CONTENT_LEN_MAX
{
	return @"EDAM_NOTE_CONTENT_LEN_MAX";
}

-(id)EDAM_NOTEBOOK_NAME_LEN_MIN
{
	return @"EDAM_NOTEBOOK_NAME_LEN_MIN";
}

-(id)EDAM_NOTEBOOK_NAME_LEN_MAX
{
	return @"EDAM_NOTEBOOK_NAME_LEN_MAX";
}

-(id)EDAM_NOTEBOOK_NAME_REGEX
{
	return @"EDAM_NOTEBOOK_NAME_REGEX";
}

-(id)EDAM_NOTEBOOK_STACK_LEN_MIN
{
	return @"EDAM_NOTEBOOK_STACK_LEN_MIN";
}

-(id)EDAM_NOTEBOOK_STACK_LEN_MAX
{
	return @"EDAM_NOTEBOOK_STACK_LEN_MAX";
}

-(id)EDAM_NOTEBOOK_STACK_REGEX
{
	return @"EDAM_NOTEBOOK_STACK_REGEX";
}

-(id)EDAM_PUBLISHING_URI_LEN_MIN
{
	return @"EDAM_PUBLISHING_URI_LEN_MIN";
}

-(id)EDAM_PUBLISHING_URI_LEN_MAX
{
	return @"EDAM_PUBLISHING_URI_LEN_MAX";
}

-(id)EDAM_PUBLISHING_URI_REGEX
{
	return @"EDAM_PUBLISHING_URI_REGEX";
}

-(id)EDAM_PUBLISHING_URI_PROHIBITED
{
	return @"EDAM_PUBLISHING_URI_PROHIBITED";
}

-(id)EDAM_PUBLISHING_DESCRIPTION_LEN_MIN
{
	return @"EDAM_PUBLISHING_DESCRIPTION_LEN_MIN";
}

-(id)EDAM_PUBLISHING_DESCRIPTION_LEN_MAX
{
	return @"EDAM_PUBLISHING_DESCRIPTION_LEN_MAX";
}

-(id)EDAM_PUBLISHING_DESCRIPTION_REGEX
{
	return @"EDAM_PUBLISHING_DESCRIPTION_REGEX";
}

-(id)EDAM_SAVED_SEARCH_NAME_LEN_MIN
{
	return @"EDAM_SAVED_SEARCH_NAME_LEN_MIN";
}

-(id)EDAM_SAVED_SEARCH_NAME_LEN_MAX
{
	return @"EDAM_SAVED_SEARCH_NAME_LEN_MAX";
}

-(id)EDAM_SAVED_SEARCH_NAME_REGEX
{
	return @"EDAM_SAVED_SEARCH_NAME_REGEX";
}

-(id)EDAM_USER_PASSWORD_LEN_MIN
{
	return @"EDAM_USER_PASSWORD_LEN_MIN";
}

-(id)EDAM_USER_PASSWORD_LEN_MAX
{
	return @"EDAM_USER_PASSWORD_LEN_MAX";
}

-(id)EDAM_USER_PASSWORD_REGEX
{
	return @"EDAM_USER_PASSWORD_REGEX";
}

-(id)EDAM_NOTE_TAGS_MAX
{
	return @"EDAM_NOTE_TAGS_MAX";
}

-(id)EDAM_NOTE_RESOURCES_MAX
{
	return @"EDAM_NOTE_RESOURCES_MAX";
}

-(id)EDAM_USER_TAGS_MAX
{
	return @"EDAM_USER_TAGS_MAX";
}

-(id)EDAM_USER_SAVED_SEARCHES_MAX
{
	return @"EDAM_USER_SAVED_SEARCHES_MAX";
}

-(id)EDAM_USER_NOTES_MAX
{
	return @"EDAM_USER_NOTES_MAX";
}

-(id)EDAM_USER_NOTEBOOKS_MAX
{
	return @"EDAM_USER_NOTEBOOKS_MAX";
}

-(id)EDAM_USER_RECENT_MAILED_ADDRESSES_MAX
{
	return @"EDAM_USER_RECENT_MAILED_ADDRESSES_MAX";
}

-(id)EDAM_USER_MAIL_LIMIT_DAILY_FREE
{
	return @"EDAM_USER_MAIL_LIMIT_DAILY_FREE";
}

-(id)EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM
{
	return @"EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM";
}

-(id)EDAM_USER_UPLOAD_LIMIT_FREE
{
	return @"EDAM_USER_UPLOAD_LIMIT_FREE";
}

-(id)EDAM_USER_UPLOAD_LIMIT_PREMIUM
{
	return @"EDAM_USER_UPLOAD_LIMIT_PREMIUM";
}

-(id)EDAM_NOTE_SIZE_MAX_FREE
{
	return @"EDAM_NOTE_SIZE_MAX_FREE";
}

-(id)EDAM_NOTE_SIZE_MAX_PREMIUM
{
	return @"EDAM_NOTE_SIZE_MAX_PREMIUM";
}

-(id)EDAM_RESOURCE_SIZE_MAX_FREE
{
	return @"EDAM_RESOURCE_SIZE_MAX_FREE";
}

-(id)EDAM_RESOURCE_SIZE_MAX_PREMIUM
{
	return @"EDAM_RESOURCE_SIZE_MAX_PREMIUM";
}

-(id)EDAM_USER_LINKED_NOTEBOOK_MAX
{
	return @"EDAM_USER_LINKED_NOTEBOOK_MAX";
}

-(id)EDAM_NOTEBOOK_SHARED_NOTEBOOK_MAX
{
	return @"EDAM_NOTEBOOK_SHARED_NOTEBOOK_MAX";
}

@end